# Generated by Django 3.1.5 on 2021-02-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_jela', models.CharField(max_length=50)),
                ('opis_jela', models.CharField(max_length=200)),
                ('tip_jela', models.CharField(choices=[('Predjelo', 'Predjelo'), ('Glavno jelo', 'Glavno jelo'), ('Desert', 'Desert'), ('Salata', 'Salata')], max_length=20)),
                ('cijena', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Jelo',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_menija', models.CharField(max_length=100)),
                ('jelo_na_meniju', models.ManyToManyField(related_name='jela', to='catering.Jelo', verbose_name='Jela u meniju')),
            ],
            options={
                'verbose_name': 'Meni',
                'verbose_name_plural': 'Meniji',
            },
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=100)),
                ('datum_usluge', models.DateField()),
                ('kontakt_broj', models.CharField(max_length=15)),
                ('broj_posluzitelja', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('napomena', models.TextField()),
                ('narucitelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('odabrani_meni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.menu')),
            ],
            options={
                'verbose_name_plural': 'Narudžbe',
            },
        ),
    ]
